# Generated by Django 5.0.3 on 2024-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kategori',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='aciklama',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='resim',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='baslik',
            new_name='title',
        ),
    ]
