# Generated by Django 5.0.3 on 2024-03-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Ürün Kategori', 'verbose_name_plural': 'Ürün Kategorileri'},
        ),
    ]
