# Generated by Django 5.0.3 on 2024-03-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Kategori', 'verbose_name_plural': 'Blog Kategorileri'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_home',
        ),
    ]
